replicaCount: 2

image:
  repository: product-service
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3001
  targetPort: 3001
  nodePort: 30008

container:
  port: 3001

resources: {}